import type { Request } from '../../../packages/shared/src';

export const mockRequests: Request[] = [
  {
    id: "rev-reviewed",
    type: "review",
    contactId: "contact-4",
    contactSnapshot: {
      id: "contact-4",
      displayName: "Alex Rivera",
    },
    ownerId: "owner-1",
    createdAt: new Date("2026-01-08"),
    status: "reviewed",
    messageSequence: {
      id: "seq-4",
      stage: 2,
      messages: [
        {
          id: "msg-4",
          sequenceId: "seq-4",
          orderInSequence: 1,
          content: "Hi Alex! Quick favor—could you share a few words about your experience with us?",
          generatedAt: new Date("2026-01-08"),
          sentAt: new Date("2026-01-08T09:00:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4b",
          sequenceId: "seq-4",
          orderInSequence: 2,
          content: "Just a quick reminder—our feedback form takes about 30 seconds: rave.com/feedback",
          generatedAt: new Date("2026-01-09"),
          sentAt: new Date("2026-01-09T10:15:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4c",
          sequenceId: "seq-4",
          orderInSequence: 3,
          content: "Thanks for the feedback, Alex! If you're open to it, here is our Google review link: g.page/rave/review",
          generatedAt: new Date("2026-01-10"),
          sentAt: new Date("2026-01-10T11:05:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4d",
          sequenceId: "seq-4",
          orderInSequence: 4,
          content: "Friendly reminder—your Google review really helps: g.page/rave/review",
          generatedAt: new Date("2026-01-12"),
          sentAt: new Date("2026-01-12T09:20:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4e",
          sequenceId: "seq-4",
          orderInSequence: 5,
          content: "Thanks for leaving a review, Alex—we really appreciate it.",
          generatedAt: new Date("2026-01-14T09:30:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-4f",
          sequenceId: "seq-4",
          orderInSequence: 6,
          content: "If you'd like, I can reply publicly on Google with a thank-you.",
          generatedAt: new Date("2026-01-15T09:30:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
    feedback: {
      id: "fb-2",
      requestId: "rev-reviewed",
      emojiRating: { value: 5, submittedAt: new Date("2026-01-10"), meetsThreshold: true },
      feedbackText: {
        text: "Super easy process and great service. Happy to recommend!",
        submittedAt: new Date("2026-01-10"),
        googleReviewSubmitted: true,
      },
      linkedGoogleReview: { googleReviewId: "google-review-1", confirmedAt: new Date("2026-01-13") },
    },
    outcome: {
      id: "out-1",
      requestId: "rev-reviewed",
      reviewOutcome: { completed: true, googleReviewSubmitted: true, submittedAt: new Date("2026-01-13") },
    },
  },
];
