import type { Request } from './types';

export const mockRequests: Request[] = [
  // REVIEW STAGES
  // Rules: review requests should show the right data for each status.
  // - new: has an unsent first message only
  // - requested: has the first message sent, plus upcoming reminders
  // - feedback-received: includes feedback + a sent Google review link
  // - reviewed: includes review outcome + next unsent reply message
  // - replied: includes a sent reply message (no next action)
  {
    id: "rev-new",
    type: "review",
    contactId: "contact-1",
    contactName: "Jane Doe",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-15"),
    status: "new",
    messageSequence: {
      id: "seq-1",
      stage: 1,
      messages: [
        {
          id: "msg-1",
          sequenceId: "seq-1",
          orderInSequence: 1,
          content: "Hi Jane! Quick favor—could you share a few words about your experience with us?",
          generatedAt: new Date("2026-01-15"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-1b",
          sequenceId: "seq-1",
          orderInSequence: 2,
          content: "Just a quick reminder—our feedback form takes about 30 seconds: rave.com/feedback",
          generatedAt: new Date("2026-01-17T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
  },
  {
    id: "rev-requested",
    type: "review",
    contactId: "contact-2",
    contactName: "Mike Johnson",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-12"),
    status: "requested",
    messageSequence: {
      id: "seq-2",
      stage: 1,
      messages: [
        {
          id: "msg-2",
          sequenceId: "seq-2",
          orderInSequence: 1,
          content: "Hi Mike! Here is a quick feedback form about your experience: rave.com/feedback",
          generatedAt: new Date("2026-01-12"),
          sentAt: new Date("2026-01-12T09:00:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-2b",
          sequenceId: "seq-2",
          orderInSequence: 2,
          content: "Quick reminder on that feedback form—happy to help if you have any questions.",
          generatedAt: new Date("2026-01-14T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-2c",
          sequenceId: "seq-2",
          orderInSequence: 3,
          content: "Checking in one last time on the feedback form. It only takes about 30 seconds.",
          generatedAt: new Date("2026-01-16T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-2d",
          sequenceId: "seq-2",
          orderInSequence: 4,
          content: "If you already filled it out, thank you so much—just let me know.",
          generatedAt: new Date("2026-01-18T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 5, maxAttempts: 3, nextScheduledAt: new Date("2026-01-14T10:00:00") },
    },
  },
  {
    id: "rev-feedback",
    type: "review",
    contactId: "contact-3",
    contactName: "Sarah Chen",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-10"),
    status: "feedback-received",
    messageSequence: {
      id: "seq-3",
      stage: 2,
      messages: [
        {
          id: "msg-3",
          sequenceId: "seq-3",
          orderInSequence: 1,
          content: "Thanks for the feedback, Sarah! If you're open to it, here is our Google review link: g.page/rave/review",
          generatedAt: new Date("2026-01-10"),
          sentAt: new Date("2026-01-11T11:00:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-3b",
          sequenceId: "seq-3",
          orderInSequence: 2,
          content: "Friendly reminder—your Google review really helps: g.page/rave/review",
          generatedAt: new Date("2026-01-12T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-3c",
          sequenceId: "seq-3",
          orderInSequence: 3,
          content: "If you already left the review, thank you so much!",
          generatedAt: new Date("2026-01-14T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 2, nextScheduledAt: new Date("2026-01-12T10:00:00") },
    },
    feedback: {
      id: "fb-1",
      requestId: "rev-feedback",
      emojiRating: { value: 5, submittedAt: new Date("2026-01-10T18:30:00"), meetsThreshold: true },
      feedbackText: { text: "Great experience!", submittedAt: new Date("2026-01-10T18:30:00") },
    },
  },
  {
    id: "rev-reviewed",
    type: "review",
    contactId: "contact-4",
    contactName: "Alex Rivera",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-08"),
    status: "reviewed",
    messageSequence: {
      id: "seq-4",
      stage: 2,
      messages: [
        {
          id: "msg-4",
          sequenceId: "seq-4",
          orderInSequence: 1,
          content: "Hi Alex! Quick favor—could you share a few words about your experience with us?",
          generatedAt: new Date("2026-01-08"),
          sentAt: new Date("2026-01-08T09:00:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4b",
          sequenceId: "seq-4",
          orderInSequence: 2,
          content: "Just a quick reminder—our feedback form takes about 30 seconds: rave.com/feedback",
          generatedAt: new Date("2026-01-09"),
          sentAt: new Date("2026-01-09T10:15:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4c",
          sequenceId: "seq-4",
          orderInSequence: 3,
          content: "Thanks for the feedback, Alex! If you're open to it, here is our Google review link: g.page/rave/review",
          generatedAt: new Date("2026-01-10"),
          sentAt: new Date("2026-01-10T11:05:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4d",
          sequenceId: "seq-4",
          orderInSequence: 4,
          content: "Friendly reminder—your Google review really helps: g.page/rave/review",
          generatedAt: new Date("2026-01-12"),
          sentAt: new Date("2026-01-12T09:20:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-4e",
          sequenceId: "seq-4",
          orderInSequence: 5,
          content: "Thanks for leaving a review, Alex—we really appreciate it.",
          generatedAt: new Date("2026-01-14T09:30:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-4f",
          sequenceId: "seq-4",
          orderInSequence: 6,
          content: "If you'd like, I can reply publicly on Google with a thank-you.",
          generatedAt: new Date("2026-01-15T09:30:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
    feedback: {
      id: "fb-2",
      requestId: "rev-reviewed",
      emojiRating: { value: 5, submittedAt: new Date("2026-01-10"), meetsThreshold: true },
      feedbackText: {
        text: "Super easy process and great service. Happy to recommend!",
        submittedAt: new Date("2026-01-10"),
        googleReviewSubmitted: true,
      },
      linkedGoogleReview: { googleReviewId: "google-review-1", confirmedAt: new Date("2026-01-13") },
    },
    outcome: {
      id: "out-1",
      requestId: "rev-reviewed",
      reviewOutcome: { completed: true, googleReviewSubmitted: true, submittedAt: new Date("2026-01-13") },
    },
  },
  {
    id: "rev-replied",
    type: "review",
    contactId: "contact-10",
    contactName: "Priya Patel",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-06"),
    status: "replied",
    messageSequence: {
      id: "seq-9",
      stage: 2,
      messages: [
        {
          id: "msg-9",
          sequenceId: "seq-9",
          orderInSequence: 1,
          content: "Hi Priya! Quick favor—could you share a few words about your experience with us?",
          generatedAt: new Date("2026-01-06"),
          sentAt: new Date("2026-01-06T09:15:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-9b",
          sequenceId: "seq-9",
          orderInSequence: 2,
          content: "Thanks for the feedback, Priya! If you're open to it, here is our Google review link: g.page/rave/review",
          generatedAt: new Date("2026-01-08"),
          sentAt: new Date("2026-01-08T11:00:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-9c",
          sequenceId: "seq-9",
          orderInSequence: 3,
          content: "Thanks for leaving a review, Priya—we really appreciate it.",
          generatedAt: new Date("2026-01-10"),
          sentAt: new Date("2026-01-10T09:30:00"),
          status: "sent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
    feedback: {
      id: "fb-3",
      requestId: "rev-replied",
      emojiRating: { value: 5, submittedAt: new Date("2026-01-08"), meetsThreshold: true },
      feedbackText: {
        text: "Fantastic experience from start to finish.",
        submittedAt: new Date("2026-01-08"),
        googleReviewSubmitted: true,
      },
    },
    outcome: {
      id: "out-3",
      requestId: "rev-replied",
      reviewOutcome: { completed: true, googleReviewSubmitted: true, submittedAt: new Date("2026-01-09") },
    },
  },

  // REFERRAL STAGES
  {
    id: "ref-new",
    type: "referral",
    contactId: "contact-5",
    contactName: "David Kim",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-15"),
    status: "new",
    messageSequence: {
      id: "seq-5",
      stage: 1,
      messages: [
        {
          id: "msg-5",
          sequenceId: "seq-5",
          orderInSequence: 1,
          content: "Hi David—could you intro me to Jamie? I drafted a quick note for you to send.",
          generatedAt: new Date("2026-01-15"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-5b",
          sequenceId: "seq-5",
          orderInSequence: 2,
          content: "Just a reminder on that intro—happy to help tweak the note.",
          generatedAt: new Date("2026-01-17T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
  },
  {
    id: "ref-requested",
    type: "referral",
    contactId: "contact-6",
    contactName: "Lisa Wong",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-14"),
    status: "requested",
    messageSequence: {
      id: "seq-6",
      stage: 1,
      messages: [
        {
          id: "msg-6",
          sequenceId: "seq-6",
          orderInSequence: 1,
          content: "Thanks Lisa! Here is the intro draft—feel free to tweak before sending.",
          generatedAt: new Date("2026-01-14"),
          sentAt: new Date("2026-01-14T09:15:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-6b",
          sequenceId: "seq-6",
          orderInSequence: 2,
          content: "Quick nudge on the intro draft whenever you have a moment.",
          generatedAt: new Date("2026-01-16T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-6c",
          sequenceId: "seq-6",
          orderInSequence: 3,
          content: "If you've already sent it, thank you so much.",
          generatedAt: new Date("2026-01-18T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3, nextScheduledAt: new Date("2026-01-16T10:00:00") },
    },
  },
  {
    id: "ref-drafted",
    type: "referral",
    contactId: "contact-7",
    contactName: "Tom Wilson",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-12"),
    status: "referral-drafted",
    messageSequence: {
      id: "seq-7",
      stage: 1,
      messages: [
        {
          id: "msg-7",
          sequenceId: "seq-7",
          orderInSequence: 1,
          content: "Your intro draft is ready to send to Alex.",
          generatedAt: new Date("2026-01-12"),
          sentAt: new Date("2026-01-12T10:30:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-7b",
          sequenceId: "seq-7",
          orderInSequence: 2,
          content: "Reminder: you can send or edit the intro draft whenever you are ready.",
          generatedAt: new Date("2026-01-14T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
        {
          id: "msg-7c",
          sequenceId: "seq-7",
          orderInSequence: 3,
          content: "Happy to tweak the intro if you want a different tone.",
          generatedAt: new Date("2026-01-16T10:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3, nextScheduledAt: new Date("2026-01-14T10:00:00") },
    },
    referralData: {
      id: "ref-data-1",
      requestId: "ref-drafted",
      referrerId: "contact-7",
      targetContactIds: ["contact-8"],
      referrerInput: { rawInput: "They need help with SEO", inputMethod: "voice", submittedAt: new Date() },
      messageVariants: {
        variants: [],
        selectedVariant: "casual",
        finalMessage: "Hey, check out Jamie for SEO help!",
      },
    },
  },
  {
    id: "ref-introduced",
    type: "referral",
    contactId: "contact-9",
    contactName: "Emma Davis",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-05"),
    status: "introduced",
    messageSequence: {
      id: "seq-8",
      stage: 1,
      messages: [
        {
          id: "msg-8",
          sequenceId: "seq-8",
          orderInSequence: 1,
          content: "Thanks Emma—intro sent. I will follow up directly.",
          generatedAt: new Date("2026-01-06"),
          sentAt: new Date("2026-01-06T08:45:00"),
          status: "sent",
          channel: "sms",
        },
        {
          id: "msg-8b",
          sequenceId: "seq-8",
          orderInSequence: 2,
          content: "Thanks again for making the intro!",
          generatedAt: new Date("2026-01-08T09:00:00"),
          status: "unsent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 3 },
    },
    outcome: { id: "out-2", requestId: "ref-introduced", referralOutcome: { introSuccessful: true } },
  },
  {
    id: "ref-thanked",
    type: "referral",
    contactId: "contact-11",
    contactName: "Carlos Ortega",
    ownerId: "owner-1",
    createdAt: new Date("2026-01-03"),
    status: "thanked",
    messageSequence: {
      id: "seq-10",
      stage: 1,
      messages: [
        {
          id: "msg-10",
          sequenceId: "seq-10",
          orderInSequence: 1,
          content: "Thanks again for the intro, Carlos—really appreciate it.",
          generatedAt: new Date("2026-01-04"),
          sentAt: new Date("2026-01-04T09:00:00"),
          status: "sent",
          channel: "sms",
        },
      ],
      cadenceSettings: { intervalDays: 7, maxAttempts: 1 },
    },
    outcome: { id: "out-4", requestId: "ref-thanked", referralOutcome: { introSuccessful: true, markedByUserAt: new Date("2026-01-04") } },
  },
];
